export { default as Badge } from './components/atoms/Badge.svelte';
export { default as Button } from './components/atoms/Button.svelte';
export { default as EmailRow } from './components/molecules/EmailRow.svelte';
export { default as MetricCard } from './components/molecules/MetricCard.svelte';
export { default as NavItem } from './components/molecules/NavItem.svelte';
export { default as SearchInput } from './components/molecules/SearchInput.svelte';
export { default as Topbar } from './components/organisms/Topbar.svelte';
export { default as Sidebar } from './components/organisms/Sidebar.svelte';
export { default as MetricGrid } from './components/organisms/MetricGrid.svelte';
export { default as InboxTable } from './components/organisms/InboxTable.svelte';
export { default as ClassificationPanel } from './components/organisms/ClassificationPanel.svelte';
export { default as InboxWorkspace } from './components/organisms/InboxWorkspace.svelte';
export { default as DashboardShell } from './components/templates/DashboardShell.svelte';
export { inboxEmails } from './data/inbox.js';
